DROP TABLE IF EXISTS elements;

CREATE TABLE elements (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          quantity INT NOT NULL,
                          price INT NOT NULL,
                          description VARCHAR(1000)
);